part of 'ffmpeg_execution.dart';

extension _FfmpegMobileExecution on FfmpegExecutor {
  /// Mobile-specific video export using ffmpeg_kit_flutter
  Stream<ExportProgress> _exportVideoMobile({
    required Project project,
    required List<Chunk> chunks,
    required String outputFilePath,
    required String tempDir,
    String? tempFontsDir,
    AspectConversionMode? conversionMode,
    bool enableAudioCrossfade = false,
    double audioCrossfadeDuration = 0.05,
    bool enableStudioSound = false,
    AudioMasteringConfig? audioMastering,
    RetentionProgressBarConfig? progressBarConfig,
    BackgroundMusicConfig? backgroundMusic,
    List<SpeakerInterval>? speakerIntervals,
    List<BRollClip>? bRollClips,
  }) async* {
    LoggerService.instance.log(LogLevel.action, 'FfmpegExporter',
        'Starting video export to: $outputFilePath (Mobile)');
    yield const ExportProgress(progress: 0.0, status: 'rendering');

    if (tempFontsDir != null) {
      final String fontsConfigDir = p.dirname(tempFontsDir);
      await FFmpegKitConfig.setFontDirectory(fontsConfigDir);
      // Overwrite the autogenerated fonts.conf to exclude scanning /system/fonts (which consumes massive memory on low-end devices)
      try {
        final fontsConfFile = File(p.join(fontsConfigDir, 'fonts.conf'));
        final customConfig = '''
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>$tempFontsDir</dir>
    <cachedir>$tempFontsDir/cache</cachedir>
    <config></config>
</fontconfig>
''';
        await fontsConfFile.writeAsString(customConfig);
        LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
            'Customized fonts.conf to exclude system fonts and save memory.');
      } catch (e) {
        LoggerService.instance.log(LogLevel.warning, 'FfmpegExporter',
            'Failed to customize fonts.conf: $e');
      }
    }

    final segmentsToUse = _buildSegments(project);
    final trimmedChunks = _buildTrimmedChunks(chunks, segmentsToUse);

    double totalDuration = 0.0;
    for (final seg in segmentsToUse) {
      totalDuration += ((seg.end ?? 0.0) - (seg.start ?? 0.0));
    }
    if (totalDuration <= 0.0) {
      totalDuration = project.duration;
    }

    final isProjectVertical = project.height > project.width;
    final Project projectForExport =
        (conversionMode != null && !isProjectVertical)
            ? (SchemaClones.cloneProjectDeep(project)
              ..width = 1080
              ..height = 1920)
            : project;

    final assContent = generateAssScript(projectForExport, trimmedChunks);
    final assPath = p.join(tempDir, '${project.projectId}_export.ass');
    final assFile = File(assPath);
    await assFile.writeAsString(assContent);
    LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
        'Generated ASS subtitle timing script. Path: $assPath');
    LoggerService.instance
        .log(LogLevel.info, 'FfmpegExporter', 'ASS Content:\n$assContent');

    // FIX: render to a staging path with the correct container extension so FFmpeg
    // can determine the output muxer, and only move it over the final file on success.
    final outputFile = File(outputFilePath);
    final ext = p.extension(outputFilePath);
    final safeExt = ext.isNotEmpty ? ext : '.mp4';
    final stagingPath = '${p.withoutExtension(outputFilePath)}_partial$safeExt';
    final stagingFile = File(stagingPath);
    if (stagingFile.existsSync()) {
      try {
        await stagingFile.delete();
      } catch (e) {
        LoggerService.instance.debug('Failed to delete pre-existing stagingFile: $e');
      }
    }

    // FIX (Issue #2b, CapStudio 1.0 audit): everything from here down that can
    // throw is wrapped in try/finally so temp files (ASS script, fonts.conf,
    // converted emoji PNGs) are always cleaned up, even if collectEmojiAndSfx,
    // convertToPngOnMobile, or buildFilterComplex throws partway through.
    // This mirrors the guarantee _exportVideoDesktop already had — previously
    // only the desktop path cleaned up reliably on exception; mobile leaked.
    // success/temporaryConvertedFiles are declared here (outside the try) so
    // both the finally block and the post-try yield can see them.
    bool success = false;
    final List<String> temporaryConvertedFiles = [];

    try {
      final List<(WordSchema, String)> validEmojiWords = [];
      final List<SfxExportItem> sfxItems = [];
      await collectEmojiAndSfx(trimmedChunks, project.config.emojiPack,
          validEmojiWords, sfxItems, tempDir);
      LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
          'Found ${validEmojiWords.length} emojis and ${sfxItems.length} sound effects to mix.');

      // On mobile, FFmpeg's decoder does not support animated WebP.
      // We convert WebP emojis to static PNGs using Flutter's native image decoder.
      final List<(WordSchema, String)> processedEmojiWords = [];
      for (final item in validEmojiWords) {
        final processedPath = await convertToPngOnMobile(item.$2, tempDir);
        processedEmojiWords.add((item.$1, processedPath));
        if (processedPath != item.$2) {
          temporaryConvertedFiles.add(processedPath);
        }
        if (item.$2.contains('rendered_emoji_')) {
          temporaryConvertedFiles.add(item.$2);
        }
      }

      final List<String> ffmpegArgs = ['-y', '-i', project.videoPath];
      for (final item in processedEmojiWords) {
        final path = item.$2.toLowerCase();
        final isAnimated = await isAnimatedFile(item.$2);
        if (path.endsWith('.gif') || (path.endsWith('.png') && isAnimated)) {
          ffmpegArgs.addAll(['-ignore_loop', '0', '-i', item.$2]);
        } else if (path.endsWith('.webp')) {
          ffmpegArgs.addAll(['-loop', '0', '-i', item.$2]);
        } else {
          ffmpegArgs.addAll(['-i', item.$2]);
        }
      }

      final validBRoll = (bRollClips ?? [])
          .where((c) => c.mediaPath.isNotEmpty && File(c.mediaPath).existsSync())
          .toList();
      for (final clip in validBRoll) {
        if (clip.isVideo) {
          ffmpegArgs.addAll(['-stream_loop', '-1', '-i', clip.mediaPath]);
        } else {
          ffmpegArgs.addAll(['-loop', '1', '-i', clip.mediaPath]);
        }
      }

      if (backgroundMusic != null && backgroundMusic.hasMusic) {
        ffmpegArgs.addAll(['-i', backgroundMusic.musicPath!]);
      }
      for (final item in sfxItems) {
        ffmpegArgs.addAll(['-i', item.resolvedPath]);
      }

      int? sourceWidth;
      int? sourceHeight;
      bool hasAudio = true;
      try {
        final metadata = await probeVideoMetadata(
          videoPath: project.videoPath,
          ffprobePath: FfmpegLocator.instance.resolveFfprobe(
            configured: SettingsService.instance.ffmpegCliPath,
          ),
        );
        if (metadata != null) {
          sourceWidth = metadata.width;
          sourceHeight = metadata.height;
          hasAudio = metadata.hasAudio;
        }
      } catch (e) {
        LoggerService.instance.debug('probeVideoMetadata failed on mobile export: $e');
      }

      final filterComplex = buildVideoFilterComplex(
        project: projectForExport,
        segmentsToUse: segmentsToUse,
        trimmedChunks: trimmedChunks,
        validEmojiWords: processedEmojiWords,
        sfxItems: sfxItems,
        assPath: assPath,
        tempFontsDir: tempFontsDir,
        conversionMode: conversionMode,
        sourceWidth: sourceWidth,
        sourceHeight: sourceHeight,
        enableAudioCrossfade: enableAudioCrossfade,
        audioCrossfadeDuration: audioCrossfadeDuration,
        hasAudio: hasAudio,
        enableStudioSound: enableStudioSound,
        audioMastering: audioMastering,
        progressBarConfig: progressBarConfig,
        backgroundMusic: backgroundMusic,
        speakerIntervals: speakerIntervals,
        bRollClips: validBRoll,
      );

      ffmpegArgs.addAll(['-filter_complex', filterComplex]);
      ffmpegArgs.addAll(['-map', '[v_final]']);
      ffmpegArgs.addAll(['-map', '[a_final]']);

      final settings = SettingsService.instance;
      final List<String> activeCodecArgs = [];
      bool isAndroidHardware = false;

      if (Platform.isIOS) {
        activeCodecArgs.addAll([
          '-c:v',
          'h264_videotoolbox',
          '-b:v',
          '8M',
          '-pix_fmt',
          'yuv420p',
          '-threads',
          '${_getOptimalExportThreads()}',
        ]);
      } else if (Platform.isAndroid &&
          settings.useGpu &&
          processedEmojiWords.isEmpty) {
        isAndroidHardware = true;
        activeCodecArgs.addAll([
          '-c:v',
          'h264_mediacodec',
          '-b:v',
          '8M',
          '-pix_fmt',
          'yuv420p',
          '-threads',
          '${_getOptimalExportThreads()}',
        ]);
      } else {
        activeCodecArgs.addAll([
          '-c:v',
          'libx264',
          '-preset',
          'ultrafast',
          '-crf',
          '23',
          '-pix_fmt',
          'yuv420p',
          '-threads',
          '${_getOptimalExportThreads()}',
        ]);
      }

      final String containerFormat = safeExt.replaceFirst('.', '').toLowerCase();
      final List<String> primaryArgs = [
        ...ffmpegArgs,
        ...activeCodecArgs,
        '-c:a',
        'aac',
        '-b:a',
        '192k',
        '-t',
        totalDuration.toStringAsFixed(3),
        '-f',
        containerFormat,
        stagingPath
      ];
      LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
          'Mobile FFmpeg primary args: ${primaryArgs.join(" ")}');

      await for (final prog
          in _executeMobileFFmpeg(primaryArgs, totalDuration)) {
        yield prog;
        if (prog.status == 'completed') success = true;
      }

      // Fallback if Android hardware encoder fails
      if (!success && isAndroidHardware) {
        LoggerService.instance.log(LogLevel.warning, 'FfmpegExporter',
            'Android hardware h264_mediacodec export failed. Falling back to software libx264.');
        yield const ExportProgress(
            progress: 0.1,
            status: 'rendering',
            error: 'Hardware export failed. Retrying with software encoder...');

        if (stagingFile.existsSync()) {
          try {
            await stagingFile.delete();
          } catch (e) {
            LoggerService.instance.debug('Failed to delete stagingFile before mobile fallback: $e');
          }
        }

        final List<String> fallbackCodecArgs = [
          '-c:v',
          'libx264',
          '-preset',
          'ultrafast',
          '-crf',
          '23',
          '-pix_fmt',
          'yuv420p',
          '-threads',
          '${_getOptimalExportThreads()}',
        ];
        final List<String> fallbackArgs = [
          ...ffmpegArgs,
          ...fallbackCodecArgs,
          '-c:a',
          'aac',
          '-b:a',
          '192k',
          '-t',
          totalDuration.toStringAsFixed(3),
          '-f',
          containerFormat,
          stagingPath
        ];
        LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
            'Mobile FFmpeg fallback args: ${fallbackArgs.join(" ")}');

        await for (final prog
            in _executeMobileFFmpeg(fallbackArgs, totalDuration)) {
          yield prog;
          if (prog.status == 'completed') success = true;
        }
      }

      // Promote the staged render to the final path before entering finally
      if (success) {
        if (stagingFile.existsSync()) {
          try {
            if (outputFile.existsSync()) {
              await outputFile.delete();
            }
            try {
              await stagingFile.rename(outputFilePath);
            } catch (_) {
              await stagingFile.copy(outputFilePath);
              if (stagingFile.existsSync()) await stagingFile.delete();
            }
            LoggerService.instance.log(LogLevel.info, 'FfmpegExporter',
                'Mobile export promoted staging file to $outputFilePath');
          } catch (e) {
            success = false;
            LoggerService.instance.log(LogLevel.error, 'FfmpegExporter',
                'Failed to finalize staged export: $e');
          }
        } else {
          LoggerService.instance.log(LogLevel.warning, 'FfmpegExporter',
              'Export reported success but no staging file was produced at $stagingPath');
        }
      }
    } finally {
      // Always runs — on success, on normal failure, AND on a thrown exception.
      try {
        await assFile.delete();
      } catch (e) {
        LoggerService.instance.debug('Failed to delete temp assFile on mobile: $e');
      }
      // Only delete staging output if export failed or threw an error
      if (!success) {
        try {
          if (stagingFile.existsSync()) await stagingFile.delete();
        } catch (e) {
          LoggerService.instance.debug('Failed to delete stagingFile in mobile finally: $e');
        }
      }

      // Clean up temporary fonts.conf
      if (tempFontsDir != null) {
        try {
          final configDir = p.dirname(tempFontsDir);
          final fontsConfFile = File(p.join(configDir, 'fonts.conf'));
          if (fontsConfFile.existsSync()) {
            await fontsConfFile.delete();
          }
        } catch (e) {
          LoggerService.instance.debug('Failed to delete fonts.conf on mobile: $e');
        }
      }

      // Clean up temporary converted PNG files on mobile
      for (final path in temporaryConvertedFiles) {
        try {
          final f = File(path);
          if (f.existsSync()) await f.delete();
        } catch (e) {
          LoggerService.instance.debug('Failed to delete temporaryConvertedFile: $e');
        }
      }
    }

    if (success) {
      yield const ExportProgress(progress: 1.0, status: 'completed');
    } else {
      yield const ExportProgress(
        progress: 0.0,
        status: 'failed',
        error: 'FFmpeg mobile export failed. Check logs.',
      );
    }
  }

  Stream<ExportProgress> _executeMobileFFmpeg(
      List<String> args, double duration) async* {
    final progressCtrl = StreamController<ExportProgress>();
    progressCtrl.add(const ExportProgress(progress: 0.2, status: 'rendering'));

    try {
      final session = await FFmpegKit.executeWithArgumentsAsync(
        args,
        (session) async {
          try {
            final rc = await session.getReturnCode();
            final success = ReturnCode.isSuccess(rc);

            // Print all FFmpeg logs for diagnostics
            final logs = await session.getLogs();
            for (final log in logs) {
              final msg = log.getMessage();
              // Skip harmless/spammy warnings that pollute logs and diagnostics
              if (msg.contains('Changing video frame properties') ||
                  msg.contains('all_channel_counts') ||
                  msg.contains('filter context - w:') ||
                  msg.contains('Guessed Channel Layout')) {
                continue;
              }
              final level = log.getLevel();
              final isError = level == Level.avLogError ||
                  level == Level.avLogFatal ||
                  level == Level.avLogPanic;
              final isWarning = level == Level.avLogWarning;
              LoggerService.instance.log(
                isError
                    ? LogLevel.error
                    : isWarning
                        ? LogLevel.warning
                        : LogLevel.info,
                'FFmpegSessionLog',
                msg,
              );
            }
            final failStackTrace = await session.getFailStackTrace();
            if (failStackTrace != null && failStackTrace.isNotEmpty) {
              LoggerService.instance.log(
                LogLevel.error,
                'FFmpegSessionFailStackTrace',
                failStackTrace,
              );
            }

            if (!progressCtrl.isClosed) {
              progressCtrl.add(ExportProgress(
                progress: success ? 1.0 : 0.0,
                status: success ? 'completed' : 'failed',
                error: success
                    ? null
                    : 'FFmpeg mobile export failed with return code $rc',
              ));
              await progressCtrl.close();
            }
          } catch (e, stackTrace) {
            LoggerService.instance.log(
                LogLevel.error, 'FfmpegExporter', 'Complete callback error: $e',
                stackTrace: stackTrace);
            if (!progressCtrl.isClosed) {
              progressCtrl.add(ExportProgress(
                  progress: 0.0, status: 'failed', error: e.toString()));
              await progressCtrl.close();
            }
          } finally {
            _activeSession = null;
          }
        },
        null,
        (Statistics statistics) {
          final time = statistics.getTime();
          if (time > 0 && duration > 0) {
            final double currentSec = time / 1000.0;
            final double progress = (currentSec / duration).clamp(0.0, 1.0);
            if (!progressCtrl.isClosed) {
              progressCtrl
                  .add(ExportProgress(progress: progress, status: 'rendering'));
            }
          }
        },
      );
      _activeSession = session;
    } catch (e) {
      if (!progressCtrl.isClosed) {
        progressCtrl.add(ExportProgress(
            progress: 0.0, status: 'failed', error: e.toString()));
        await progressCtrl.close();
      }
      rethrow;
    }

    yield* progressCtrl.stream;
  }
}
